### PR TITLE
a few additions and changes

### PR DESCRIPTION
**Pull request by Glloyd**
various map tweaks to the changes made to the kitchen, cargo, and the bridge powernet.

Remaps a few of the holodecks, adds in multiple new ones.

### CODE REVIEW

**Comment by Glloyd** [comment]
I left the upload and the other things mentioned in the feedback for you. I'll take another quick look through once that's done, but besides that I think this'll be more or less good to merge.

**Comment by Glloyd** [comment]
I realized I wasn't clear there, this PR is fine to merge. I was referring to the full PR.

**Comment by CPU-Blanc** [comment]
Wow, it'd be nice if Github notified me this went through, sorry for the delay!

Couple of small issues I've picked up on.

New space holoarea carp spawn landmarks need the `can_copy` var set to 1, else the holodeck won't bring them over and spawn them. Var was added and defaults to false to ensure no jank with existing landmarks and shuttles or whatelse.
New button for the kitchen-holodeck shutters doesn't have the correct tag set on it, it's currently linked to the shutter in the hallway.

**Comment by Glloyd** [comment]
@CPU-Blanc fixed the aforementioned issues and what Raz mentioned on discord

**Comment by CPU-Blanc** [comment]
Thanks! I'll run through some of the requests posted in discord then we should hopefully be good pending your final review

**Pull request merged**
